[readnote]
name='读书笔记'
sort=0
    [[readnote.sites]]
    url='https://mubu.com/doc/2TG2Oiz1mU'
    name='秒杀系统读书笔记'
    favicon='https://mubu.com/favicon.ico'
    desc='极客时间秒杀笔记'
    openType='iframe'
    config.iframe-style='height:100%;width:100%;min-height:1000px'

[tools]
name='工具'
sort=1
    [[tools.sites]]
    url='https://www.666email.com'
    name='666Email'
    desc='10分钟邮箱'
    [[tools.sites]]
    url='https://haveibeenpwned.com'
    name='社工库'
    [[tools.sites]]
    url='http://www.stickpng.com'
    name='PNG搜索'
    [[tools.sites]]
    url='https://www.typingclub.com'
    name='TypingClub'
    desc='标准指法联系'
    [[tools.sites]]
    url='https://www.processon.com'
    name='ProcessOn'
    desc='在线流程图'
    [[tools.sites]]
    url='http://zhangweijie.cn/hq-icon/'
    name='icon查询'
    [[tools.sites]]
    url='https://regexr.com/'
    name='在线正则'
    [[tools.sites]]
    url='https://colors.ichuantong.cn/'
    name='古典配色'

[blog]
name='订阅'
sort=2
    [[blog.sites]]
    url='http://tech.lede.com'
    name='网易乐得技术团队'
    desc='网易乐得技术分享'
    [[blog.sites]]
    url='https://tech.meituan.com'
    name='美团技术团队'
    desc='美团技术分享'
    [[blog.sites]]
    url='http://vitrun.github.io'
    name='Food for Thought'
    desc='小志'
    [[blog.sites]]
    url='https://blog.alswl.com'
    name='Log4D'
    desc='3D'
    [[blog.sites]]
    url='https://javadoop.com'
    name='JavaDoop'
    desc='众安保险大佬Java分享'
    [[blog.sites]]
    url='https://gmem.site'
    name='绿色记忆'
    desc='全栈-汪震'
    [[blog.sites]]
    url='http://hengyunabc.github.io'
    name='横云断岭'
    desc='阿里-断岭'
    [[blog.sites]]
    url='http://hedengcheng.com'
    name='何登成的技术博客'
    desc='阿里DBA主管'
    [[blog.sites]]
    url='http://www.guxingke.com'
    name='孤星可'
    desc='堆糖小k'
    [[blog.sites]]
    url='https://www.flysnow.org'
    name='飞雪无情的博客'
    desc='Go实战笔记作者'
    [[blog.sites]]
    url='https://skyao.io/'
    name='敖小剑'
    desc='Service Mesh布道师'
    [[blog.sites]]
    url='https://hongjiang.info/'
    name='宏江大佬'
    desc='挖财-宏江'
    [[blog.sites]]
    url='http://tech.dianwoda.com/'
    name='点我达'
    desc='点我达技术博客'
    [[blog.sites]]
    url='https://tech.songxiaocai.com/posts/index.html/'
    name='宋小菜'
    desc='宋小菜技术博客'
    [[blog.sites]]
    url='https://www.yumingyuan.me/'
    name='鱼头的博客'
    desc='极客-鱼头'
    [[blog.sites]]
    url='https://draveness.me/'
    name='面向信仰编程'
    desc='draveness'

[forum]
name='资讯'
sort=3
    [[forum.sites]]
    url='https://www.tonymacx86.com/'
    name='tonymacx86'
    desc='黑苹果论坛'
    [[forum.sites]]
    url='https://www.v2ex.com/'
    name='V2EX'
    desc='V2EX论坛'
    [[forum.sites]]
    url='https://www.52pojie.cn/forum-21-1.html'
    name='52破解'
    desc='52破解资源站'
    [[forum.sites]]
    url='https://www.iplaysoft.com/'
    name='异次元软件'
    desc='软件资讯'
    [[forum.sites]]
    url='https://sspai.com/'
    name='少数派'
    desc='苹果派'
    [[forum.sites]]
    url='http://free.apprcn.com/'
    name='反斗限免'
    desc='APP限免资讯'
    [[forum.sites]]
    url='https://www.waerfa.com/'
    name='Mac玩儿法'
    desc='Mac软件资讯'
    [[forum.sites]]
    url='http://www.chuapp.com'
    name='触乐'
    desc='触乐游戏资讯'
    [[forum.sites]]
    url='https://www.ifanr.com'
    name='爱泛儿'
    [[forum.sites]]
    url='https://www.chiphell.com/'
    name='Chiphell'
    [[forum.sites]]
    url='http://www.dgtle.com/'
    name='数字尾巴'

[resource]
name='资源'
sort=4
    [[resource.sites]]
    url='https://www.yunpanjingling.com'
    name='云盘精灵'
    [[resource.sites]]
    url='http://ddrk.me/'
    name='低端影视'
    [[resource.sites]]
    url='https://www.sq688.com/'
    name='无损音乐'
    [[resource.sites]]
    url='https://unsplash.com/'
    name='unsplash'
    [[resource.sites]]
    url='http://www.btbtt.me/'
    name='BT之家'
